<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="Testcontainers.Kafka" />
		<PackageReference Include="Testcontainers.PostgreSql" />
		<PackageReference Include="FluentAssertions" />
		<PackageReference Include="xunit.v3" />
		<PackageReference Include="xunit.runner.visualstudio" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference
		  Include="..\..\..\..\src\Workers\PaymentOutbox\Conflux.Payment.OutboxPublisher\Conflux.Payment.OutboxPublisher.csproj" />
	</ItemGroup>

</Project>