<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Conflux.Kafka\Conflux.Kafka.csproj" />
    <PackageReference Include="Confluent.Kafka" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Services\Catalog\Conflux.Catalog\Conflux.Catalog.csproj" />
  </ItemGroup>
</Project>
