<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Yarp.ReverseProxy" />
    <PackageReference Include="StackExchange.Redis" />
	
    <ProjectReference Include="..\..\BuildingBlocks\Conflux.Observability\Conflux.Observability.csproj" />
  </ItemGroup>

</Project>